# Generated by Django 5.2.4 on 2026-02-22 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.TextField(blank=True, help_text='What do you love learning about?')),
                ('plan', models.CharField(choices=[('FREE', 'Free Student'), ('BASIC', 'Pro Student'), ('ULTRA', 'Ultra Explorer')], default='FREE', max_length=10)),
                ('questions_asked', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
