# Generated by Django 5.2.4 on 2026-02-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='history_chapter',
            field=models.IntegerField(default=1, help_text='Current chapter in History Class'),
        ),
    ]
