# Generated by Django 5.2.4 on 2026-02-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_history_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='day_number',
            field=models.IntegerField(default=1, help_text='The day number this conversation belongs to'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='day_question_count',
            field=models.IntegerField(default=0, help_text='Questions asked in the current day'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='history_chapter',
            field=models.IntegerField(default=1, help_text='Current day/chapter in History Class'),
        ),
    ]
